### PR TITLE
Add Tune permissions and referrer receiver to AndroidManifest.xml

### PR DESCRIPTION
**Pull request by wInevitable**
@patbenatar the third step in the puzzle. Apparently, this is how you update `AndroidManifest.xml` per the readme. Tune steps shown here: https://developers.tune.com/sdk/segment-sdk-integration/#code-platform-android

Adds user permissions and a referrer receiver. Now to figure out how to test if the app still runs with all of these changes..

### CODE REVIEW

**Comment by patbenatar** [comment]
:+1: — is there an equivalent for iOS?

**Comment by wInevitable** [comment]
@patbenatar not exactly - if we use deep/universal links we have to add some code to each one:

`[Tune applicationDidOpenURL:[url absoluteString] sourceApplication:sourceApplication];`

https://developers.tune.com/sdk/segment-sdk-integration/#code-platform-ios

**Comment by patbenatar** [comment]
But nothing special to do on iOS for install attribution?

**Comment by wInevitable** [comment]
Nothing special that I see!

**Comment by patbenatar** [comment]
:+1: — let's keep this in PR until you've been able to successfully test

**Pull request closed without merging**
